---
application:
  name: authorizer
  base_url: http://localhost:8080

database:
  addr: localhost:5432
  username: postgres
  password: dev
  database: authorizer

http_server:
  addr: localhost:8080

logger:
  level: debug
  pretty: true

allowed_redirect_urls:
  - http://localhost:8080

google:
  client_id: string
  client_secret: string
