---
application:
  name: authorizer
  pprof: true

http_server:
  addr: localhost:8080

logger:
  level: debug
  pretty: false

mongo:
  addr: mongodb://dev:dev@localhost:27017/?retryWrites=true&w=majority
  database_name: commondb

oauth_general:
  server_redirect_uri: http://localhost:8080
  allowed_client_redirect_uris:
    - https://localhost:8080
    - https://google.com

oauth_google:
  redirect_uri: "https://accounts.google.com/o/oauth2/v2/auth"
  scopes: "https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile"
  client_id: ""
  client_secret: ""
  token_endpoint: "https://oauth2.googleapis.com/token"
