name: CI
on:
  # Runs on all pull-request events on all branches.
  pull_request:

permissions:
  # Can only read the source code.
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --fix=false --timeout 5m

      - name: Test
        run: CGO_ENABLED=1 go test -race ./...

      - name: Build
        run: go build cmd/authorizer/main.go

  deploy:
    name: Deploy
    needs: ci
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: ./.github/actions/deploy
       with:
        server_ip: ${{ fromJSON(secrets.SSH_DETAILS).server_ip }}
        ssh_private_key: ${{ fromJSON(secrets.SSH_DETAILS).ssh_private_key }}
        ssh_username: ${{ fromJSON(secrets.SSH_DETAILS).ssh_username }}
        service_name: authorizer
        service_port: 8080
        configs_yaml: ${{ secrets.CONFIGS_YAML }}
